### ISSUE TITLE
Conflict between local pip and conda pip for package taxtastic

### ISSUE THREAD

**Issue by blinard-BIOINFO** [phylo42/PEWO#1]
If taxtastic is installed locally via pip, it mingles with the taxtastic installation of the conda environment.
Conda has its own internal pip command but somehow, it cannot isolate both ?

Example: taxtastic 0.8.5 installed locally via pip + 0.8.11 install via PEWO conda environement:

```
Traceback (most recent call last):
  File "/home/benclaff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/home/benclaff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/benclaff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (taxtastic 0.8.5 (/home/benclaff/.local/lib/python3.6/site-packages), Requirement.parse('taxtastic==0.8.11'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/benclaff/softwares/miniconda3/envs/PEWO/bin/taxit", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/benclaff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3112, in <module>
    @_call_aside
  File "/home/benclaff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3096, in _call_aside
    f(*args, **kwargs)
  File "/home/benclaff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3125, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/benclaff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 580, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/benclaff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 593, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/benclaff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'taxtastic==0.8.11' distribution was not found and is required by the application
```

**Comment by blinard-BIOINFO** [comment]
So far, the only solution is to completely unistall taxtastic from the local pip installation, keeping only the conda installation...
